version: '3.8'
services:
  web:
    build:
      context: .
    image: bustime_demo:uv-202201
    volumes:
      - .:/shared
    ports:
      - 3000:3000
    working_dir: /shared
    environment:
      PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: ${COMPOSE_PROJECT_NAME}
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
